### ISSUE TITLE
What is the purpose of rewriting the feed origin?

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/dat-rssreader-app#3]
These feeds demonstrate an issue where feed entry links are rewritten to match the origin that served the feed. I can’t quite figure out the purpose of rewriting feed origins in this manner. It breaks FeedPress feeds entirely and only coincidently work with FeedBurner.

* https://feedpress.me/mozblog
* https://feed.ctrl.blog/latest
* https://feeds.feedburner.com/d0od

I don’t quite understand why origins are rewritten here.

**Comment by pfrazee** [comment]
Just need to double-check, because there are two RSS apps in our ecosystem, which app are you reporting this for (which URL)? This app is at dat://rss-reader-pfrazee.hashbase.io/. I don't *recall* rewriting the feed origin in this app, and those examples work in this app.

**Comment by da2x** [comment]
I’m reporting for this one. :wink: 

The code is here: https://github.com/beakerbrowser/dat-rssreader-app/blob/6e9a0f4e55b24c31298619ce7370ad27d58b70de/lib/com/inbox.js#L25-L44

**Comment by da2x** [comment]
So what I’m seeing for my own feed, for example is the following:

Feed fetched from `https://feed.ctrl.blog/latest` (origin: feed.ctrl.blog) and it contains a link like `https://www.ctrl.blog/entry/the-dweb#feed`, but this link is rewritten to `https://feed.ctrl.blog/entry/the-dweb#feed`.

**Comment by pfrazee** [comment]
Oh. Hmm. Yeah I don't remember why I did that. I'll dig into it, 1 sec.

**Comment by da2x** [comment]
I though I’d fix it in a pull request, but I really couldn’t figure out the reason why it was done in the first place. Maybe some feeds served over dat:// include links to https:// and those would be accessible over da:// by rewriting the origin? To do this properly, it would require the use of /.well-known/dat or the DNS based auto-discovery method, however. But I’m really not sure if this is the original reason or not.

Secondarily: the app assumes the origin is the homepage of the feed, which is an assumption that doesn’t hold true for the gazillions of feeds served through a feed delivery services like FeedPress and FeedBurner. (Home pages can be auto-discovered be by looking for `//link[rel="self"][type="text/html"][href]` in the feed itself.)

**Comment by pfrazee** [comment]
> Maybe some feeds served over dat:// include links to https:// and those would be accessible over dat:// by rewriting the origin?

Yeah I just came back to comment, that is why, but it's also not needed anymore because Beaker now does what you suggested -- it detects when there's a dat version and redirects you. We can remove it.

**Comment by pfrazee** [comment]
I'll remove it and publish

**Comment by da2x** [comment]
Great! Thanks!

By the by, is there an API that this app can use to resolve things like this? It’s better for performance if the app tries to resolve HTTPS and save the DAT variant while it’s updating the feeds rather than having the user click a HTTPS link and then wait for it all to happen.

Likewise, when subscribing to a HTTPS feed it would be useful if the app would attempt to rewrite things on the fly.

**Comment by pfrazee** [comment]
There's [DatArchive.resolveName()](https://beakerbrowser.com/docs/apis/dat#datarchive-resolvename)

**Comment by pfrazee** [comment]
Okay should be fixed, lmk if you have any more issues.
